### ISSUE TITLE
Add more ticker options for GBP, please

### ISSUE THREAD

**Issue by knorthfield** [MacWallet/MacWallet#3]
For instance:
- https://api.bitcoinaverage.com/ticker/GBP
- https://bitpay.com/api/rates

**Comment by jonasschnelli** [comment]
added some GBP tickers with commit https://github.com/MacWallet/MacWallet/commit/90cf38cb794b70b372cd0695676eff1d98f113af

**Comment by knorthfield** [comment]
Wow, awesome, quick work, thanks.
