### ISSUE TITLE
Popovers not getting focus (v 0.12)

### ISSUE THREAD

**Issue by pjv** [MacWallet/MacWallet#4]
Running on Mavericks, when I try to password protect the wallet, i get the popover that says "Enter a password" but that popover does not get focus and even when I click on it and the password field, I am unable to type in there.

The same thing happens in the send coins popover.

Note that I am testing the client and I have no btc in there at all.

Maybe I will fork and try to fix these things and send you a PR, but I am not sure when I will have time to do that, so I thought I would give you the issue report in case you can get to it before I have a chance.

**Comment by jonasschnelli** [comment]
Nice catch. Will test that issue on 10.9 soon.
You can also switch to testnet under "Network -> Network: Bitcoin" (you should get a prompt window).

You can then send you some test-bitcoins over http://tpfaucet.appspot.com (just in case you'd like to test a bit more).

**Comment by pjv** [comment]
I switched to the test net as you suggested and when I then restarted to activate the switch, the problem I reported had disappeared. I switched back to the production network, restarted again, and the problem remained solved.

So it appears that it was only on the initial launch of the app that the problem appeared. Please note that I had previously installed and looked at v 0.1 and installed v 0.12 on top of it this morning, so there were presumably a pre-existing wallet, prefs, etc. hanging around already from version 0.1.

**Comment by jonasschnelli** [comment]
@pjv do you still have problems with this (with version 0.12.1 (3))?

**Comment by pjv** [comment]
Hi @jonasschnelli,

as far as i can tell, it was an artifact of the initial launch. since i haven't uninstalled and re-installed, and have kept the wallet encrypted, i haven't seen this problem again since that first launch. maybe it's a "priming the pump" kind of thing with an uninitialized list or something?

anyway, i'll close this issue and if someone else sees it, they can re-open.
